Cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats

  # resources :cats, only: [:index] do
  #   resources :cats_rental_requests, only: [:new]
  # end
  resources :cats_rental_requests, only: [:new]


end

Cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  COLOR = %w(yellow green black white brown orange)
  validates :birth_date, :color, :name, :sex, presence: true
  validates :color, inclusion: { in: COLOR,
    message: "%{value} is not a valid color"
  }

  has_many :cats_rental_requests,
  dependent: :destroy

  def self.color
      COLOR
  end
end

Cats/app/models/cats_rental_request.rb
# == Schema Information
#
# Table name: cats_rental_requests
#
#  id         :bigint(8)        not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatsRentalRequest < ApplicationRecord
  STATUS = %w(PENDING APPROVED DENIED)
  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion: { in: STATUS,
    message: "Error, that is not a valid status!"
  }
  validate :overlapping_requests

  belongs_to :cat,
  foreign_key: :cat_id,
  class_name: :Cat

  def overlapping_requests
    collisions = CatsRentalRequest
    .select(:start_date, :end_date)
    .where("cat_id = :cat_id", {cat_id: cat_id})
    .where("start_date BETWEEN :start_date AND :end_date OR
    end_date between :start_date AND :end_date", {start_date: start_date,
      end_date: end_date})
    unless collisions.empty?
      self.errors[:errors] << "This request collides with an already approved request!"
    end
    collisions 
  end


end

Cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all

    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages,status: 422
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: 422
    end
  end

private
  def cat_params
    params.require(:cat).permit(:birth_date, :name,:sex,:color,:description)
  end
end

Cats/app/controllers/cats_rental_requests_controller.rb
class CatsRentalRequestsController < ApplicationController
  def new
    @request = CatsRentalRequest.new
    render :new
  end
end

Cats/app/helpers/application_helper.rb
module ApplicationHelper
end

Cats/app/helpers/cats_helper.rb
module CatsHelper
end

Cats/app/helpers/cats_rental_requests_helper.rb
module CatsRentalRequestsHelper
end

Cats/app/views/cats/_cats.html.erb
<!-- <table>
  <%# @cat.each do |k, v|  %>
  <tr>
    <td> <%#= "#{k}" %> </td>
    <td> <%#= "#{v}" %> </td>
  </tr> 
  <%# end %>
</table>  -->

Cats/app/views/cats/_form.html.erb
<% if type == :new %>
  <% action_url = cats_url %>
  <% button_type = 'Register Cat' %>
<% else %>
  <% action_url = cat_url(cat) %>
  <% button_type = 'Update Information' %>
<% end %>

<form action="<%=action_url%>" method="post">
  <%if type == :edit%>
    <input type="hidden" name="_method" value="patch">
  <%end%>
  <input type="text" name="cat[name]" value="<%=cat.name%>">
  <input type="date" name="cat[birth_date]" value ="<%=cat.birth_date%>">
  <%if cat.sex== "M"%>
    <input type="radio" id='Male' name="cat[sex]" value="M" checked>
    <label for="Male">Male</label>
    <input type="radio" id='Female' name="cat[sex]" value="F">
    <label for="Female">Female</label>
  <%else%>
  <input type="radio" id='Male' name="cat[sex]" value="M">
  <label for="Male">Male</label>
  <input type="radio" id='Female' name="cat[sex]" value="F" checked>
  <label for="Female">Female</label>
  <%end%>
  <select name="cat[color]">
    <%if type == :new%>
      <option selected="selected" disabled value=""> Select </option>
    <%else%>
      <option value="<%=cat.color %>" > <%= cat.color %> </option>
    <%end%>
    <% Cat.color.each do |color| %>
      <%next if color == cat.color%>
      <option value="<%=color %>"> <%= color %> </option>
    <% end %>
  </select>
  <br>
  <textarea name="cat[description]" rows="10" cols="75" placeholder="Describe your cat here..."><%= cat.description %></textarea>
  <input type="submit" value="<%=button_type%>">
</form>

<a href="<%=cats_url%>"> Return to index </a>

Cats/app/views/cats/edit.html.erb
<%= render 'form', cat: @cat, type: :edit %> 

Cats/app/views/cats/index.html.erb
<table>
<% @cats.each do |cat| %>
  <tr>
    <td> <a href="<%=cat_url(cat)%>"><%= cat.name %></a></td>
    <td> <a href="<%=edit_cat_url(cat)%>"> Update </a> </td>
  </tr>
<%end%>
</table>

<a href="<%= new_cat_url %>"> Add Cat </a>

Cats/app/views/cats/new.html.erb
<%= render 'form', cat: @cat, type: :new %>

Cats/app/views/cats/show.html.erb
<table>
  <tr>
    <td> Name </td>
    <td><%=@cat.name%> </td>
  </tr>
  <tr>
    <td> Birth Date </td>
    <td> <%=@cat.birth_date%> </td>
  </tr>
  <tr>
    <td> Sex </td>
    <td><%=@cat.sex%></td>
  </tr>
  <tr>
    <td> Color </td>
    <td><%=@cat.color%></td>
  </tr>
</table>

<a href="<%=cats_url%>"> Index </a>
<a href="<%=edit_cat_url(@cat)%>"> Update </a>

Cats/app/views/cats_rental_requests/new.html.erb
<select>
  <% Cat.all.each do |cat|%>
    <option value="<%=cat.name %>"><%=cat.name%></option>
  <% end %>
</select> 

Cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>